apiVersion: v2
name: loki
description: Loki - log aggregation system by Grafana Labs
type: application
version: 0.1.0
dependencies:
  - name: loki
    version: 6.6.3  # 최신 버전으로 교체 가능
    repository: https://grafana.github.io/helm-charts
