loki:
  auth_enabled: false

  storage:
    type: filesystem
    bucketNames:
      chunks: dummy-chunks
      ruler: dummy-ruler
      admin: dummy-admin

  storage_config:
    boltdb:
      directory: /var/loki/index
    filesystem:
      directory: /var/loki/chunks

  schema_config:
    configs:
      - from: 2024-06-10
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 168h

  commonConfig:
    replication_factor: 1

