loki:
  auth_enabled: false
  storage:
    filesystem:
      directory: /var/loki
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin

  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 168h

  commonConfig:
    replication_factor: 1
