loki:
  fullnameOverride: loki
  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

  persistence:
    enabled: true
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  service:
    type: ClusterIP

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  monitoring:
    selfMonitoring:
      enabled: false
