replicaCount: 2

image:
  repository: nginx
  tag: "1.23.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80



ingress:
  enabled: true
  hosts:
    - host: prometheus.local
      paths:
        - path: /
          pathType: Prefix
