replicaCount: 1

image:
  repository: postgres
  tag: "14"
  pullPolicy: IfNotPresent

postgresql:
  username: postgres
  password: "0000"
  database: literature

service:
  type: ClusterIP
  port: 5432
