replicaCount: 1

image:
  repository: donghk77/literature
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

env:
  - name: DATABASE_URL
    value: "postgres://postgres:0000@postgresql-postgresql:5432/literature"
