{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-alertmanager
data:
  alertmanager.yml: |
{{ toYaml .Values.alertmanager.config | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus.fullname" . }}-alertmanager
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus.fullname" . }}-alertmanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prometheus.fullname" . }}-alertmanager
    spec:
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - containerPort: {{ .Values.alertmanager.service.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
      volumes:
        - name: config
          configMap:
            name: {{ include "prometheus.fullname" . }}-alertmanager
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}-alertmanager
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: {{ .Values.alertmanager.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "prometheus.fullname" . }}-alertmanager
{{- end }}
