apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
  selector:
    app.kubernetes.io/name: {{ include "prometheus.fullname" . }}
