# 공통 네임스페이스
namespace: monitoring

# 1) nginx-ingress 설정
ingress-nginx:
  controller:
    service:
      type: LoadBalancer
    metrics:
      enabled: true

# 2) Prometheus 설정
prometheus:
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - host: prometheus.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific

  server:
    ingress:
      enabled: true
      hosts:
        - host: prometheus.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific


# 3) Grafana 설정
grafana:
  admin:
    existingSecret: grafana-admin-credentials
  ingress:
    enabled: true
    hosts:
      - grafana.example.com
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

# 4) Loki 설정
loki:
  # 1) commonConfig를 빈 테이블로 정의 → 헬퍼는 여기서 분기 통과
  commonConfig: {}

  # 2) enterprise 기능 완전 비활성화 → tpl 호출 방지
  enterprise:
    enabled: false
    config: {}

  # 3) persistence 등 나머지 설정...
  persistence:
    enabled: true
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  ingress:
    enabled: true
    hosts:
      - host: loki.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific

  config:
    auth_enabled: false
    server:
      http_listen_port: 3100
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h
    ruler:
      storage:
        type: local
        local:
          directory: /data/loki/rules
