# 네임스페이스 (CreateNamespace=true 옵션으로 만들어집니다)
namespace: monitoring

# ───────────────────────────────────────────────────────────────
# 1) ingress-nginx 설정
ingress-nginx:
  controller:
    service:
      type: LoadBalancer
    metrics:
      enabled: true
    # Admission Webhook 비활성화 (인증서 에러 방지)
    admissionWebhooks:
      enabled: false

# ───────────────────────────────────────────────────────────────
# 2) Prometheus 설정
prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.example.com
    path: /
    pathType: ImplementationSpecific

  alertmanager:
    ingress:
      enabled: true
      hosts:
        - host: prometheus.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific

# ───────────────────────────────────────────────────────────────
# 3) Grafana 설정
grafana:
  admin:
    existingSecret: grafana-admin-credentials
  ingress:
    enabled: true
    hosts:
      - grafana.example.com
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

# ───────────────────────────────────────────────────────────────
# 4) Loki-Stack 설정
loki-stack:
  # 차트 내부 공통 스토리지 분기 우회 (버전에 따라 필요)
  commonConfig: {}
  enterprise:
    enabled: false
    config: {}

  persistence:
    enabled: true
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  ingress:
    enabled: true
    hosts:
      - host: loki.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific

  config:
    auth_enabled: false
    server:
      http_listen_port: 3100

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h

    ruler:
      storage:
        type: local
        local:
          directory: /data/loki/rules
