# 공통 네임스페이스
namespace: monitoring

# 1) nginx-ingress 설정
ingress-nginx:
  controller:
    service:
      type: LoadBalancer
    metrics:
      enabled: true

# 2) Prometheus 설정
prometheus:
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - host: prometheus.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific

  server:
    ingress:
      enabled: true
      hosts:
        - host: prometheus.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific


# 3) Grafana 설정
grafana:
  admin:
    existingSecret: grafana-admin-credentials
  ingress:
    enabled: true
    hosts:
      - grafana.example.com
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

# 4) Loki 설정
loki:
  # 1) 오브젝트 스토리지 대신 로컬 파일시스템 사용
  storage_config:
    boltdb_shipper:
      # 인덱스 저장 폴더
      active_index_directory: /data/loki/index
      shared_store: filesystem
    filesystem:
      # 청크 저장 폴더
      directory: /data/loki/chunks

  # 2) enterprise 기능 비활성화 (tpl 함수 에러 방지)
  enterprise:
    enabled: false
    config: {}

  # 3) 기존 config는 여기에만 작성
  config:
    auth_enabled: false

    server:
      http_listen_port: 3100

    schema_config:
      # (필요한 schema_config 작성)
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h

    ruler:
      storage:
        type: local
        local:
          directory: /data/loki/rules

    # ...그 외 필요한 설정 계속...
