# 공통 네임스페이스
namespace: monitoring

# 1) nginx-ingress 설정
ingress-nginx:
  controller:
    service:
      type: LoadBalancer
    metrics:
      enabled: true

# 2) Prometheus 설정
prometheus:
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - host: prometheus.example.com    # 문자열이 아니라 map[string]string
          paths:
            - path: /
              pathType: ImplementationSpecific

  server:
    ingress:
      enabled: true
      hosts:
        - host: prometheus.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific

# 3) Grafana 설정
grafana:
  admin:
    existingSecret: grafana-admin-credentials
  ingress:
    enabled: true
    hosts:
      - grafana.example.com
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

# 4) Loki-Stack 설정
loki-stack:
  commonConfig: {}    # optional, helm-chart 버전에 따라 필요할 수 있습니다
  enterprise:
    enabled: false
    config: {}

  persistence:
    enabled: true
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  ingress:
    enabled: true
    hosts:
      - host: loki.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific

  config:
    auth_enabled: false
    server:
      http_listen_port: 3100
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h
    ruler:
      storage:
        type: local
        local:
          directory: /data/loki/rules
