replicaCount: 1

image:
  repository: redis
  tag: "7.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
