replicaCount: 1

image:
  repository: prom/prometheus
  tag: v2.46.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

alertmanager:
  enabled: true
  image:
    repository: prom/alertmanager
    tag: v0.25.0
  service:
    port: 9093
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'default'
    receivers:
      - name: 'default'
        email_configs:
          - to: 'oncall@example.com'

scrapeConfigs:
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:9100'
        target_label: __address__
