name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CI Build & Push Start
        uses: actions/checkout@v3

      - name: Set image tag and name
        run: | 
          echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "IMAGE=${{ secrets.DOCKER_HUB_USERNAME  }}/gitops" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME  }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD  }}
      
      - name: Build Docker image
        run: docker build -t $IMAGE:$TAG .

      - name: Push Docker image
        run: docker push $IMAGE:$TAG