name: Run Deploy

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: CI Deploy Start
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git # 작성자 식별
        run: |
          git config user.name "My_Name"
          git config user.email "My_Email@github.com"

      # 동작 흐름 예시
      # drf-backend 레포에서 새로운 커밋 → CI가 Docker 이미지 빌드 + push (donghk77/literature:abc123)
      # → 이 빌드된 이미지의 태그를 gitops 레포의 values.yaml로 업데이트
      # → Git에 푸시
      # → Argo CD가 Git 변경 감지 → 새 이미지로 자동 배포
      - name: Update Helm image tag
        run: |
          cd helm-charts/app

          # values.yaml에서 이미지 정보 갱신
          sed -i "s|repository: .*|repository: ${{ secrets.DOCKER_HUB_USERNAME }}/gitops|" values.yaml
          sed -i "s|tag: .*|tag: ${{ github.sha }}|" values.yaml

          # 변경 확인
          git add values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
