name: Run Deploy

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: CI Deploy Start
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}





          
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Update Helm image tag
        run: |
          cd helm-charts/app

          # values.yaml에서 이미지 정보 갱신
          sed -i "s|repository: .*|repository: ${{ secrets.DOCKER_HUB_USERNAME }}/gitops|" values.yaml
          sed -i "s|tag: .*|tag: ${{ github.sha }}|" values.yaml

          # 변경 확인
          git add values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
