name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: CI Test Start
        uses: actions/checkout@v3 # Code Checkout
      
      - name: Set up Python
        uses: actions/setup-python@v4 # runner 상에서 python 설치
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

      # 커버리지 추가?

      # 복잡한 의존 환경 추가? DB나 Redis